package ar.com.ventas.frame;

import ar.com.ventas.entities.Rubro2;
import ar.com.ventas.entities.Usuario;
import ar.com.ventas.main.MainFrame;
import ar.com.ventas.services.Rubro2Service;
import ar.com.ventas.services.UsuarioService;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrador
 */
public class AbmRubrosFrame extends javax.swing.JFrame {

    private List<Rubro> listadoRubro = new ArrayList<>();
//    private Integer order_num;
//    private String order_name;

    /**
     * Creates new form AbmRubroFrame
     *

     */
    public AbmRubrosFrame() {
        initComponents();
        this.llenartabla();
//        this.order_name = order_name;
//        this.order_num = order_num;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        rubroTabla = new javax.swing.JTable();
        nuevoBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        borrarBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        nuevoMenuBtn = new javax.swing.JMenuItem();
        modificarMenuBtn = new javax.swing.JMenuItem();
        eliminarMenuBtn = new javax.swing.JMenuItem();
        VovlerMenu = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        rubroTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(rubroTabla);

        nuevoBtn.setText("Nuevo");
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });

        modificarBtn.setText("Modificar");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        borrarBtn.setText("Borrar");
        borrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBtnActionPerformed(evt);
            }
        });

        archivoMenu.setText("Archivo");
        archivoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoMenuActionPerformed(evt);
            }
        });

        nuevoMenuBtn.setText("Nuevo");
        nuevoMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMenuBtnActionPerformed(evt);
            }
        });
        archivoMenu.add(nuevoMenuBtn);

        modificarMenuBtn.setText("Modificar");
        modificarMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMenuBtnActionPerformed(evt);
            }
        });
        archivoMenu.add(modificarMenuBtn);

        eliminarMenuBtn.setText("Eliminar");
        eliminarMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMenuBtnActionPerformed(evt);
            }
        });
        archivoMenu.add(eliminarMenuBtn);

        jMenuBar1.add(archivoMenu);

        VovlerMenu.setText("Volver");
        VovlerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VovlerMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(VovlerMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(modificarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(borrarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(volverBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoBtn)
                    .addComponent(modificarBtn)
                    .addComponent(volverBtn)
                    .addComponent(borrarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VovlerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VovlerMenuActionPerformed
        volver();
    }//GEN-LAST:event_VovlerMenuActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        FileReader fr = null;
        try {
            fr = new FileReader("c:/Users/permisos.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader br = new BufferedReader(fr);
        String acceso = "";
        try {
            acceso = br.readLine();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (acceso.equals("1")) {
            modificar();
        } else {
            if (acceso.equals("3")) {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                }
                JTextField field = new JTextField("");
                field.setFont(new Font("Tahoma", Font.PLAIN, 11));
                String[] options = {"Ingresar", "Regresar"};
                int result = JOptionPane.showOptionDialog(
                        null,
                        field,
                        "Autorización de USUARIO",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        0);
                switch (result) {
                    case 0:
                        int cod = Integer.valueOf(field.getText());
                        Usuario usu = null;
                        try {
                            usu = new UsuarioService().getUsuarioByCodigo(cod);
                        } catch (Exception ex) {
                            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if (usu != null) {
                            int cla = usu.getNivel();
                            if (usu.getActivo()) {
                                if (cla > 3) {
                                    JOptionPane.showMessageDialog(this, "Acceso Prohibido");
                                    break;
                                }
                                Date a = new Date();
                                if (cla == 2) {
                                    if (usu.getFecha() != null) {
                                        Date b = usu.getFecha();
                                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                        if (!sdf.format(a).equals(sdf.format(b))) {
                                            JOptionPane.showMessageDialog(this, "Acceso Vencido");
                                            break;
                                        }
                                    }
                                }
                                JTextField field2 = new JTextField("");
                                field2.setFont(new Font("Symbol", Font.PLAIN, 12));
                                String[] opts = {"Ingresar", "Regresar"};
                                int resulta = JOptionPane.showOptionDialog(
                                        null,
                                        field2,
                                        "CONTRASEÑA: " + usu.getNombre() + ", Autorización",
                                        JOptionPane.OK_CANCEL_OPTION,
                                        JOptionPane.QUESTION_MESSAGE,
                                        null,
                                        opts,
                                        0);
                                switch (resulta) {
                                    case 0:
                                        int contra = Integer.valueOf(field2.getText());
                                        if (contra == usu.getContrasena()) {
                                            modificar();
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
                                        }
                                        break;
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "USUARIO Inactivo");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "No existe el Usuario");
                        }
                        break;
                }
            }
        }
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void eliminarMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMenuBtnActionPerformed
        FileReader fr = null;
        try {
            fr = new FileReader("c:/Users/permisos.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader br = new BufferedReader(fr);
        String acceso = "";
        try {
            acceso = br.readLine();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (acceso.equals("1")) {
            borrarRubroSeleccionado();
        } else {
            if (acceso.equals("3")) {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                }
                JTextField field = new JTextField("");
                field.setFont(new Font("Tahoma", Font.PLAIN, 11));
                String[] options = {"Ingresar", "Regresar"};
                int result = JOptionPane.showOptionDialog(
                        null,
                        field,
                        "Autorización de USUARIO",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        0);
                switch (result) {
                    case 0:
                        int cod = Integer.valueOf(field.getText());
                        Usuario usu = null;
                        try {
                            usu = new UsuarioService().getUsuarioByCodigo(cod);
                        } catch (Exception ex) {
                            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if (usu != null) {
                            int cla = usu.getNivel();
                            if (usu.getActivo()) {
                                if (cla > 3) {
                                    JOptionPane.showMessageDialog(this, "Acceso Prohibido");
                                    break;
                                }
                                Date a = new Date();
                                if (cla == 2) {
                                    if (usu.getFecha() != null) {
                                        Date b = usu.getFecha();
                                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                        if (!sdf.format(a).equals(sdf.format(b))) {
                                            JOptionPane.showMessageDialog(this, "Acceso Vencido");
                                            break;
                                        }
                                    }
                                }
                                JTextField field2 = new JTextField("");
                                field2.setFont(new Font("Symbol", Font.PLAIN, 12));
                                String[] opts = {"Ingresar", "Regresar"};
                                int resulta = JOptionPane.showOptionDialog(
                                        null,
                                        field2,
                                        "CONTRASEÑA: " + usu.getNombre() + ", Autorización",
                                        JOptionPane.OK_CANCEL_OPTION,
                                        JOptionPane.QUESTION_MESSAGE,
                                        null,
                                        opts,
                                        0);
                                switch (resulta) {
                                    case 0:
                                        int contra = Integer.valueOf(field2.getText());
                                        if (contra == usu.getContrasena()) {
                                            borrarRubroSeleccionado();
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
                                        }
                                        break;
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "USUARIO Inactivo");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "No existe el Usuario");
                        }
                        break;
                }
            }
        }
    }//GEN-LAST:event_eliminarMenuBtnActionPerformed

    private void nuevoMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMenuBtnActionPerformed
        FileReader fr = null;
        try {
            fr = new FileReader("c:/Users/permisos.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader br = new BufferedReader(fr);
        String acceso = "";
        try {
            acceso = br.readLine();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (acceso.equals("1")) {
            nuevo();
        } else {
            if (acceso.equals("3")) {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                }
                JTextField field = new JTextField("");
                field.setFont(new Font("Tahoma", Font.PLAIN, 11));
                String[] options = {"Ingresar", "Regresar"};
                int result = JOptionPane.showOptionDialog(
                        null,
                        field,
                        "Autorización de USUARIO",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        0);
                switch (result) {
                    case 0:
                        int cod = Integer.valueOf(field.getText());
                        Usuario usu = null;
                        try {
                            usu = new UsuarioService().getUsuarioByCodigo(cod);
                        } catch (Exception ex) {
                            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if (usu != null) {
                            int cla = usu.getNivel();
                            if (usu.getActivo()) {
                                if (cla > 3) {
                                    JOptionPane.showMessageDialog(this, "Acceso Prohibido");
                                    break;
                                }
                                Date a = new Date();
                                if (cla == 2) {
                                    if (usu.getFecha() != null) {
                                        Date b = usu.getFecha();
                                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                        if (!sdf.format(a).equals(sdf.format(b))) {
                                            JOptionPane.showMessageDialog(this, "Acceso Vencido");
                                            break;
                                        }
                                    }
                                }
                                JTextField field2 = new JTextField("");
                                field2.setFont(new Font("Symbol", Font.PLAIN, 12));
                                String[] opts = {"Ingresar", "Regresar"};
                                int resulta = JOptionPane.showOptionDialog(
                                        null,
                                        field2,
                                        "CONTRASEÑA: " + usu.getNombre() + ", Autorización",
                                        JOptionPane.OK_CANCEL_OPTION,
                                        JOptionPane.QUESTION_MESSAGE,
                                        null,
                                        opts,
                                        0);
                                switch (resulta) {
                                    case 0:
                                        int contra = Integer.valueOf(field2.getText());
                                        if (contra == usu.getContrasena()) {
                                            nuevo();
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
                                        }
                                        break;
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "USUARIO Inactivo");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "No existe el Usuario");
                        }
                        break;
                }
            }
        }
    }//GEN-LAST:event_nuevoMenuBtnActionPerformed

    private void modificarMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMenuBtnActionPerformed
        FileReader fr = null;
        try {
            fr = new FileReader("c:/Users/permisos.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader br = new BufferedReader(fr);
        String acceso = "";
        try {
            acceso = br.readLine();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (acceso.equals("1")) {
            modificar();
        } else {
            if (acceso.equals("3")) {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                }
                JTextField field = new JTextField("");
                field.setFont(new Font("Tahoma", Font.PLAIN, 11));
                String[] options = {"Ingresar", "Regresar"};
                int result = JOptionPane.showOptionDialog(
                        null,
                        field,
                        "Autorización de USUARIO",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        0);
                switch (result) {
                    case 0:
                        int cod = Integer.valueOf(field.getText());
                        Usuario usu = null;
                        try {
                            usu = new UsuarioService().getUsuarioByCodigo(cod);
                        } catch (Exception ex) {
                            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if (usu != null) {
                            int cla = usu.getNivel();
                            if (usu.getActivo()) {
                                if (cla > 3) {
                                    JOptionPane.showMessageDialog(this, "Acceso Prohibido");
                                    break;
                                }
                                Date a = new Date();
                                if (cla == 2) {
                                    if (usu.getFecha() != null) {
                                        Date b = usu.getFecha();
                                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                        if (!sdf.format(a).equals(sdf.format(b))) {
                                            JOptionPane.showMessageDialog(this, "Acceso Vencido");
                                            break;
                                        }
                                    }
                                }
                                JTextField field2 = new JTextField("");
                                field2.setFont(new Font("Symbol", Font.PLAIN, 12));
                                String[] opts = {"Ingresar", "Regresar"};
                                int resulta = JOptionPane.showOptionDialog(
                                        null,
                                        field2,
                                        "CONTRASEÑA: " + usu.getNombre() + ", Autorización",
                                        JOptionPane.OK_CANCEL_OPTION,
                                        JOptionPane.QUESTION_MESSAGE,
                                        null,
                                        opts,
                                        0);
                                switch (resulta) {
                                    case 0:
                                        int contra = Integer.valueOf(field2.getText());
                                        if (contra == usu.getContrasena()) {
                                            modificar();
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
                                        }
                                        break;
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "USUARIO Inactivo");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "No existe el Usuario");
                        }
                        break;
                }
            }
        }

    }//GEN-LAST:event_modificarMenuBtnActionPerformed

    private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
        FileReader fr = null;
        try {
            fr = new FileReader("c:/Users/permisos.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader br = new BufferedReader(fr);
        String acceso = "";
        try {
            acceso = br.readLine();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (acceso.equals("1")) {
            nuevo();
        } else {
            if (acceso.equals("3")) {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                }
                JTextField field = new JTextField("");
                field.setFont(new Font("Tahoma", Font.PLAIN, 11));
                String[] options = {"Ingresar", "Regresar"};
                int result = JOptionPane.showOptionDialog(
                        null,
                        field,
                        "Autorización de USUARIO",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        0);
                switch (result) {
                    case 0:
                        int cod = Integer.valueOf(field.getText());
                        Usuario usu = null;
                        try {
                            usu = new UsuarioService().getUsuarioByCodigo(cod);
                        } catch (Exception ex) {
                            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if (usu != null) {
                            int cla = usu.getNivel();
                            if (usu.getActivo()) {
                                if (cla > 3) {
                                    JOptionPane.showMessageDialog(this, "Acceso Prohibido");
                                    break;
                                }
                                Date a = new Date();
                                if (cla == 2) {
                                    if (usu.getFecha() != null) {
                                        Date b = usu.getFecha();
                                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                        if (!sdf.format(a).equals(sdf.format(b))) {
                                            JOptionPane.showMessageDialog(this, "Acceso Vencido");
                                            break;
                                        }
                                    }
                                }
                                JTextField field2 = new JTextField("");
                                field2.setFont(new Font("Symbol", Font.PLAIN, 12));
                                String[] opts = {"Ingresar", "Regresar"};
                                int resulta = JOptionPane.showOptionDialog(
                                        null,
                                        field2,
                                        "CONTRASEÑA: " + usu.getNombre() + ", Autorización",
                                        JOptionPane.OK_CANCEL_OPTION,
                                        JOptionPane.QUESTION_MESSAGE,
                                        null,
                                        opts,
                                        0);
                                switch (resulta) {
                                    case 0:
                                        int contra = Integer.valueOf(field2.getText());
                                        if (contra == usu.getContrasena()) {
                                            nuevo();
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
                                        }
                                        break;
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "USUARIO Inactivo");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "No existe el Usuario");
                        }
                        break;
                }
            }
        }
    }//GEN-LAST:event_nuevoBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void borrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBtnActionPerformed
        FileReader fr = null;
        try {
            fr = new FileReader("c:/Users/permisos.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader br = new BufferedReader(fr);
        String acceso = "";
        try {
            acceso = br.readLine();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (acceso.equals("1")) {
            borrarRubroSeleccionado();
        } else {
            if (acceso.equals("3")) {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                }
                JTextField field = new JTextField("");
                field.setFont(new Font("Tahoma", Font.PLAIN, 11));
                String[] options = {"Ingresar", "Regresar"};
                int result = JOptionPane.showOptionDialog(
                        null,
                        field,
                        "Autorización de USUARIO",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        0);
                switch (result) {
                    case 0:
                        int cod = Integer.valueOf(field.getText());
                        Usuario usu = null;
                        try {
                            usu = new UsuarioService().getUsuarioByCodigo(cod);
                        } catch (Exception ex) {
                            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if (usu != null) {
                            int cla = usu.getNivel();
                            if (usu.getActivo()) {
                                if (cla > 3) {
                                    JOptionPane.showMessageDialog(this, "Acceso Prohibido");
                                    break;
                                }
                                Date a = new Date();
                                if (cla == 2) {
                                    if (usu.getFecha() != null) {
                                        Date b = usu.getFecha();
                                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                        if (!sdf.format(a).equals(sdf.format(b))) {
                                            JOptionPane.showMessageDialog(this, "Acceso Vencido");
                                            break;
                                        }
                                    }
                                }
                                JTextField field2 = new JTextField("");
                                field2.setFont(new Font("Symbol", Font.PLAIN, 12));
                                String[] opts = {"Ingresar", "Regresar"};
                                int resulta = JOptionPane.showOptionDialog(
                                        null,
                                        field2,
                                        "CONTRASEÑA: " + usu.getNombre() + ", Autorización",
                                        JOptionPane.OK_CANCEL_OPTION,
                                        JOptionPane.QUESTION_MESSAGE,
                                        null,
                                        opts,
                                        0);
                                switch (resulta) {
                                    case 0:
                                        int contra = Integer.valueOf(field2.getText());
                                        if (contra == usu.getContrasena()) {
                                            borrarRubroSeleccionado();
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
                                        }
                                        break;
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "USUARIO Inactivo");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "No existe el Usuario");
                        }
                        break;
                }
            }
        }
    }//GEN-LAST:event_borrarBtnActionPerformed

    private void archivoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoMenuActionPerformed

    }//GEN-LAST:event_archivoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbmRubrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbmRubrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbmRubrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbmRubrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbmRubrosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu VovlerMenu;
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JButton borrarBtn;
    private javax.swing.JMenuItem eliminarMenuBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JMenuItem modificarMenuBtn;
    private javax.swing.JButton nuevoBtn;
    private javax.swing.JMenuItem nuevoMenuBtn;
    private javax.swing.JTable rubroTabla;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void llenartabla() {
        try {
            Rubro2Service rubroService = new Rubro2Service();
            listadoRubro = rubroService.getAllRubros();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "error con la base de datos");
        }
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("CODIGO");
        model.addColumn("NOMBRE");
        if (listadoRubro != null && !listadoRubro.isEmpty()) {
            for (Rubro rubro : listadoRubro) {
                Object[] fila = new Object[2];
                fila[0] = rubro.getCodigo();
                fila[1] = rubro.getNombre();
                model.addRow(fila);
            }
        }
        rubroTabla.setModel(model);
    }

    private Rubro getRubroSeleccionado() {
        Rubro rubro = null;
        int filaSeleccionada = rubroTabla.getSelectedRow();
        if (filaSeleccionada != -1 && listadoRubro != null && !listadoRubro.isEmpty()) {
            rubro = listadoRubro.get(filaSeleccionada);
        } else {
            JOptionPane.showMessageDialog(this, "Rubro - Seleccione un rubro de la lista");
        }
        return rubro;
    }

    private void borrarRubroSeleccionado() {
        int filaSeleccionada = rubroTabla.getSelectedRow();
        if (filaSeleccionada != -1) {
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Desea eliminar al Rubro?",
                    "Borrar - Rubro",
                    JOptionPane.OK_CANCEL_OPTION);
            if (confirm == JOptionPane.OK_OPTION) {
                Rubro rubroABorrar = getRubroSeleccionado();
                rubroTabla.removeAll();
                try {
                    new Rubro2Service().deleteRubro(rubroABorrar);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Rubro - Error al borrar rubro. Seleccione un rubro");
                }
                this.llenartabla();
            }
        }
    }

    private void modificar() {
        Rubro rubro = this.getRubroSeleccionado();
        if (rubro != null) {
            ModificarRubroFrame mrf = new ModificarRubroFrame(rubro);
            mrf.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Rubro - seleccione un rubro");
        }
    }

    private void nuevo() {
        NuevoRubroFrame nrf = new NuevoRubroFrame();
        nrf.setVisible(true);
        this.dispose();
    }

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

}
