package ar.com.ventas.frame;

import ar.com.ventas.entities.Proveedor2;
import ar.com.ventas.services.Proveedor2Service;
import ar.com.ventas.structure.Constantes;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcela
 */
public class NuevoProveedorFrame extends javax.swing.JFrame {

    /**
     * Creates new form NuevoProveedorFrame
     */
    public NuevoProveedorFrame() {
        getContentPane().setBackground(new java.awt.Color(245, 222, 179));
        initComponents();
        limpiarCampos();
//        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        guardarBtn = new javax.swing.JButton();
        razonSocialTxt = new javax.swing.JTextField();
        codigoTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("NUEVO PROVEEDOR");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        razonSocialTxt.setText("Razón Social");
        razonSocialTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razonSocialTxtActionPerformed(evt);
            }
        });

        codigoTxt.setText("CODIGO");
        codigoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTxtActionPerformed(evt);
            }
        });
        codigoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoTxtKeyPressed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jLabel2.setText("Razon social");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(razonSocialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guardarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razonSocialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(guardarBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTxtActionPerformed

    }//GEN-LAST:event_codigoTxtActionPerformed

    private void razonSocialTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razonSocialTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razonSocialTxtActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        this.guardar();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        AbmProveedoresFrame abmP = new AbmProveedoresFrame();
        abmP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void codigoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if(verificarDuplicado()){
                razonSocialTxt.requestFocus();
            }else{
                codigoTxt.setText("");
                codigoTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_codigoTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProveedorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField razonSocialTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void guardar() {
        if (verificarDuplicado()) {
            if (validarCampos()) {
                Proveedor2 proveedor = new Proveedor2();
//                proveedor.setMail(mailTxt.getText());
//                proveedor.setObservaciones(obsTxt.getText());
                proveedor.setNombre(razonSocialTxt.getText());
                proveedor.setCodigo(Integer.valueOf(codigoTxt.getText()));
//                proveedor.setCategoriaIva(comboCategoria.getSelectedIndex());
//                proveedor.setCuit(cuitTxt.getText());
//                proveedor.setTelefono(telTxt.getText());
//                proveedor.setCelular(celularTxt.getText());
                proveedor.setActivo(true);
                proveedor.setSaldo(0.0);
//                proveedor.setContacto(contactoTxt.getText());
//                if(llevaStockChk.isSelected()){
//                    proveedor.setStock(true);
//                }else{
//                    proveedor.setStock(false);
//                }
                try {
                    new Proveedor2Service().saveProveedor(proveedor);
                    JOptionPane.showMessageDialog(this, "PROVEEDOR guardado correctamente.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Proveedor - No se puede guardar proovedor");
                    Logger.getLogger(NuevoProveedorFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                limpiarCampos();
//                llenarCombo();
            }
        }else{
            codigoTxt.setText("");
            codigoTxt.requestFocus();
        }
    }

    private void limpiarCampos() {
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(),
                Constantes.getG(),
                Constantes.getB()));
//        celularTxt.setText("");
        codigoTxt.setText("");
//        cuitTxt.setText("");
//        comboCategoria.removeAllItems();
//        comboCategoria.addItem("");
//        mailTxt.setText("");
//        obsTxt.setText("");
        razonSocialTxt.setText("");
//        telTxt.setText("");
//        contactoTxt.setText("");
//        llevaStockChk.setSelected(true);
    }

//    private void llenarCombo() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) comboCategoria.getModel();
//        model.addElement("1- Inscripto");
//        model.addElement("2- Monotributo");
//        model.addElement("3- Exento");
//        model.addElement("4- Consumidor Final");
//        comboCategoria.setModel(model);
//    }

    private boolean validarCampos() {
        if (razonSocialTxt.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Proveedor - Falta completar la razon social");
            return false;
        }
        if (codigoTxt.getText().trim().length() == 0) {
            JOptionPane.showConfirmDialog(this, "Proveedor - Falta completar el codigo");
            return false;
        }
//        if (comboCategoria.getSelectedItem() == null) {
//            JOptionPane.showMessageDialog(this, "Proveedor - Seleccione categoría de iva");
//            return false;
//        }
//        if (calleTxt.getText().trim().length() == 0) {
//            JOptionPane.showMessageDialog(this, "Proveedor - Falta completar nombre de la calle");
//            return false;
//        }
//        if (numeroTxt.getText().trim().length() == 0) {
//            JOptionPane.showMessageDialog(this, "Proveedor - Falta completar numero de la direccion");
//            return false;
//        }
//        if (cuitTxt.getText().trim().length() == 0) {
//            JOptionPane.showMessageDialog(this, "Proveedor - Falta completar cuit ");
//            return false;
//        }
//        if (cuitTxt.getText().trim().length() > 13) {
//            JOptionPane.showMessageDialog(this, "CUIT erroneo ");
//            return false;
//        }
        return true;
    }

    private boolean verificarDuplicado() {
        Boolean libre = true;
        if (!codigoTxt.getText().isEmpty()) {
            int cod = Integer.valueOf(codigoTxt.getText());
            Proveedor2 p = null;
            try {
                p = new Proveedor2Service().getProveedorByCodigo(cod);
                if (p != null) {
                    libre = false;
                }
            } catch (Exception ex) {
//                Logger.getLogger(ModificarProveedorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (libre) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Número Proveedor existente");
            return false;
        }
    }
}
