/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.main;

import ar.com.ventas.entities.Usuario;
import ar.com.ventas.services.EquipoActivoService;
import ar.com.ventas.services.UsuarioService;
import ar.com.ventas.structure.Constantes;
import ar.com.ventas.util.Globals;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author argia
 */
public class MainVendedorFrame extends javax.swing.JFrame {

    private String order_name;
    private Usuario usuario;
    private Integer order_num;
    private DecimalFormat df_order = new DecimalFormat("000");
    private DecimalFormat df_codigo = new DecimalFormat("000000");

    /**
     * Creates new form MainVendedorFrame
     */
    public MainVendedorFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
//        setExtendedState(6); // this.MAXIMIZED_BOTH
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        ingresarBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        nombreLbl = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ACCESO POR USUARIO");

        jLabel1.setText("USUARIO:");

        jLabel2.setText("CONTRASEÑA:");

        usuarioTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usuarioTxt.setText("USU");
        usuarioTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioTxtKeyPressed(evt);
            }
        });

        ingresarBtn.setText("INGRESAR");
        ingresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBtnActionPerformed(evt);
            }
        });
        ingresarBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ingresarBtnKeyPressed(evt);
            }
        });

        salirBtn.setText("SALIR");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        nombreLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLbl.setText("Nombre");

        passwordTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTxt.setText("contraseña");
        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTxtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ingresarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                        .addComponent(salirBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(nombreLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarBtn)
                    .addComponent(salirBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void usuarioTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!usuarioTxt.getText().isEmpty()) {
                passwordTxt.requestFocus();
            }
        }
// ThreadLocal<String> threadLocalValue = new ThreadLocal<>();
        //threadLocalValue.set("say Hi");
        // String value = threadLocalValue.get();
        // threadLocalValue.remove();
        // ThreadLocal<String> threadLocal = ThreadLocal.withInitial(() -> "say Hi");
    }//GEN-LAST:event_usuarioTxtKeyPressed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        salir();
    }//GEN-LAST:event_salirBtnActionPerformed

    private void ingresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBtnActionPerformed
        ingresar();
    }//GEN-LAST:event_ingresarBtnActionPerformed

    private void passwordTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!passwordTxt.getText().isEmpty()) {
                if (validar()) {
                    nombreLbl.setText(usuario.getNombre());
                    ingresarBtn.requestFocus();
                } else {
                    nombreLbl.setText("ERROR VERIFIQUE LOS DATOS INGRESADOS");
                }
            }
        }
    }//GEN-LAST:event_passwordTxtKeyPressed

    private void ingresarBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresarBtnKeyPressed
        if (evt.getKeyCode() == 10) {
            ingresar();
        }
    }//GEN-LAST:event_ingresarBtnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainVendedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainVendedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainVendedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainVendedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainVendedorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton salirBtn;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        passwordTxt.setText("");
        usuarioTxt.setText("");
//        Usuario usuario = null;
//        try {
//            usuario = new UsuarioService().getUsuarioByCodigo(1);
//        } catch (Exception ex) {
//            Logger.getLogger(MainVendedorFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private String establecerNombre() {
        InetAddress localHost;
        try {
            localHost = InetAddress.getLocalHost();
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "ERROR INGRESANDO AL SISTEMA,\nINGRESE NUEVAMENTE");
            return "";
        }
        return localHost.getHostName();
    }

    private boolean validar() {
        Integer codigo = Integer.valueOf(usuarioTxt.getText());
        try {
            usuario = new UsuarioService().getUsuarioByCodigo(codigo);
            String psw1 = usuario.getPassword();
            String psw2 = passwordTxt.getText();
            if (psw1.equals(psw2)) {
                order_name = establecerNombre();
                order_num = establecerOrden();
                return true;
            }
        } catch (Exception ex) {
//            Logger.getLogger(MainVendedorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        usuario = null;
        return false;
    }

    private Integer establecerOrden() {
        Integer i = 0;
        try {
            i = new EquipoActivoService().calcularOrden(order_name, "A");
        } catch (Exception ex) {
            Logger.getLogger(MainVendedorFrame.class.getName()).log(Level.SEVERE, null, ex);
            i = 0;
        }
        return i;
    }

    private void ingresar() {
        nombreLbl.setText(usuario.getNombre());
        String str = df_order.format(order_num)
                + df_codigo.format(usuario.getCodigo())
                + order_name;
        Globals.USR.set(str);
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void salir() {
        int a = JOptionPane.showConfirmDialog(this, "CONFIRME SALIR DEL SISTEMA",
                "Atención", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }
}
